theme: jekyll-theme-cayman
title: <img src="https://avatars1.githubusercontent.com/u/19759254?v=3&s=200"> Bract (WIP)
description: Multi-purpose, modular application initialization framework for Clojure
url: https://bract.github.io/
timezone: Asia/Kolkata
