theme: jekyll-theme-cayman
title: Bract (WIP) <a href="https://github.com/bract"><img src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png" alt="Bract on Github" style="width:42px;height:42px;border:0;"></a>
description: Multi-purpose, modular application initialization framework for Clojure
url: https://bract.github.io/
timezone: Asia/Kolkata
